config/routes.rb
FantasyFootball::Application.routes.draw do

  root "fantasy_football#home"

  resources :leagues, param: :league_id, only: [:index, :show, :new, :create] do
    member do
      get :schedule
      get :standings
      get :league_info
      get :draft
    end
    resources :teams, param: :team_id, only: [:show, :destroy] do
      get :schedule, on: :collection
      get :set_lineup, on: :member
    end
  end

  match "/join_league", to: "leagues#join", via: "get", as:"join_league"

  resources :sessions, only: [:new, :create, :destroy], path_names: { new: 'signin', destroy: 'signout' }
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"

  resources :users, except: [:index]
  match "/users/email_exists/:email_address", to: "users#email_exists", via: "get", constraints: { :email_address => /[^\/]+/ }
  match "/signup", to: "users#new", via: "get"


  namespace :api, path: '/v1', constraints: { subdomain: 'api' } do
    resources :players, only: [:index, :show]
  end
end

app/models/league.rb
class League < ActiveRecord::Base
  include LeaguesHelper

  belongs_to :league_type
  has_many :teams
  has_many :games
  has_many :users, :through => :teams
  has_many :payouts, class_name: LeaguePayout
  has_many :transactions, class_name: TeamTransaction
  has_many :team_standings, through: :teams

  validates :name, :uniqueness => { :case_sensitive => false }, :presence => true
  validates :size, :presence => true, :numericality => :only_integer
  validates :league_type_id, :presence => true, :numericality => :only_integer
  validates :entry_amount, :presence => true, :numericality => :only_integer
  validates :draft_start_date, :presence => true
  validates :season_id, presence: true
  validates :is_private, :inclusion => { in: [true, false] }

  scope :full, -> { where('size = teams_count') }
  scope :open, -> { where('size != teams_count') }
  scope :is_public, -> { where(is_private: false) }

  scope :all_leagues, -> { self.all.includes([:teams, :league_type]) }

  def user_part_of_league?(user)
    user.leagues.include?(self)
  end

  def get_nfl_week(league_week)
    nfl_week = self.nfl_start_week + league_week
    season_type_id = 1
    if(nfl_week > 17)
      season_type_id = 3
      nfl_week -= 17
    end

    { season_type_id: season_type_id, week: nfl_week }
  end

  def available_teams
    self.size - self.teams_count
  end

  def full?
    self.teams_count == self.size
  end

  def started?
    full? && (Time.now > self.draft_start_date)
  end

  def total_weeks
    self.weeks + self.playoff_weeks
  end

  def draft_transactions
    self.transactions.where(activity_type_id: ActivityType.DRAFT.id).order(:transaction_date)
  end
end

app/models/league_type.rb
class LeagueType < ActiveRecord::Base
  has_many :leagues

  def get_starting_slots
    @slots = JSON.parse(self.starting_slots_json) unless @slots
    @slots
  end

  def populate_positions(data)
    slot_data = []
    get_starting_slots.each { |slot|
      slot_data.push({ slot: slot, slot_desc: slot.join(","), data: nil })
    }

    if data
      slots = get_starting_slots
      data.each { |d|
        found_index = nil

        p = d.position.abbr
        options = slots.find_all{ |s| s.index(p) }.sort{ |s1, s2| s1.length <=> s2.length }
        found_index = slots.index(options.first) if options.length > 0
        raise "Invalid starters" unless found_index

        item = slot_data.find { |s| s[:slot] == options.first and s[:data].nil? }
        item[:data] = d if item
        slots.delete_at(found_index)
      }
    end

    slot_data
  end

  def validate_starting_positions(positions)
    valid = true
    slots = get_starting_slots

    positions.each { |p|
      found_index = nil
      puts slots.inspect
      puts p

      # Find matching options and sort them by length to use the most specific options first (i.e. WR should use WR before WR/TE)
      options = slots.find_all{ |s| s.index(p) }.sort{ |s1, s2| s1.length <=> s2.length }

      found_index = slots.index(options.first) if options.length > 0
      unless found_index
        valid = false
        break
      end
      slots.delete_at(found_index)
    }

    puts
    puts slots.inspect
    #valid = false if slots.count > 0

    valid
  end

  def validate_roster_position_limits
    limits = JSON.parse(self.position_limits_json)

  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :signed_in_user, except: [:index]
  before_action :user_team, except: [:index, :new, :create, :join]
  before_action :get_current_week, except: [:new, :create, :index, :join]

  def index
    @leagues = League.is_public.paginate(page: params[:page], per_page: 5)
    @user_leagues = current_user.leagues if signed_in?
  end

  def show
    @league = League.includes(:users).find_by(id: params[:league_id])
    redirect_to action: 'index' unless @league
  end

  def new
    @league = League.new
  end

  def create
    start_date = ""
    unless params[:league][:draft_start_date].empty? && params[:league][:draft_time].empty?
      date = params[:league][:draft_start_date]
      time = params[:league][:draft_time]
      start_date = Time.parse("#{date} #{time}").utc
    end

    @league = League.new(name: params[:league][:name], size: params[:league][:size].to_i,
                         league_type_id: params[:league][:league_type].to_i, entry_amount: params[:league][:entry_amount].to_i,
                         draft_start_date: start_date, weeks: params[:league][:duration],
                         draft_pick_time: params[:league][:draft_pick_time], fee_percent: 0.20,
                         is_private: params[:league][:visibility])

    if @league.save
      redirect_to(leagues_path, notice: "The league #{params[:league][:name]} was created successfully")
    else
      render 'new'
    end
  end

  def join
    league = League.find(params[:league_id])

    if current_user.leagues.include?(league)
      redirect_to(league, notice: "You are already part of this league")
      return
    end

    if league.full?
      redirect_to(leagues_url, notice: "League Full - Please join an available league")
      return
    end

    team_name = "#{Faker::Name.title}--#{Random.rand(1000000)}"
    Team.create!(name: team_name, user_id: current_user.id, league_id: league.id)

    redirect_to(league_path(league), notice: "Welcome to #{league.name}!")
  end

  def standings
    league = League.includes(games: [:home_team, :away_team]).find_by(id: params[:league_id])
    @current_standings = TeamStanding.for_league_week(league.id, @current_week)
    render partial: "league_standings" if params[:use_json]
  end

  def schedule
    league = League.includes(games: [:home_team, :away_team]).find_by(id: params[:league_id])

    unless league
      redirect_to(leagues_path, notice: "Selected League not found")
      return
    end

    unless league.games
      redirect_to(league_path(@league), notice: "No games have been defined yet")
    end

    @games_this_week = league.games.where(week: @current_week)
    render partial: "league_schedule" if params[:use_json]
  end

  def free_agency

  end

  def league_info
  end

  def draft
  end

  private

  def user_team
    @league = League.find_by(id: params[:league_id])
    unless @league
      redirect_to(leagues_path, notice: "Selected League not found")
      return
    end

    @user_team = Team.find_by(user_id: current_user, league_id: @league)
    redirect_to(leagues_path, notice: "You are not part of the this league") unless @user_team
  end

  def get_current_week
    render text: "Current league is not set..." unless @league

    @current_week = params[:current_week]

    unless @current_week
      if @league.started?
        current_week_data = @league.get_league_week_data_for_week
        if current_week_data
          @current_week = current_week_data.week_number
        else
          @current_week = @league.weeks
        end
      else
        @current_week = 0 #You should see your league before it starts - counting down or something...
      end
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  class WeekData
    attr_accessor :week_number,
                  :start_date

    def initialize
      self.week_number = 0
    end

    def end_date
      (start_date + 1.week - 1.day).end_of_day
    end
  end

  class DraftInfo
    attr_accessor :current_team,
                  :draft_round,
                  :draft_round_pick,
                  :last_pick_time,
                  :next_pick_time

    def draft_pick_decimal
      return "#{draft_round}.#{draft_round_pick}"
    end

    def time_left
      return (next_pick_time.to_time - Time.now.utc).round(0)
    end
  end

  def set_league_week_data
    return if self.nfl_start_week
    return if self.available_teams > 0
    return if draft_transactions.count < self.teams_count * self.roster_count

    data = get_league_week_data_for_week(1)
    nfl_game = get_nfl_week_game(data)

    unless nfl_game
      nfl_game = NflGame.where(season_type_id: 1, week: 1).order(start_time: :desc).first
      raise "The season is over" if nfl_game.start_time < data.start_date

      data.start_date = nfl_game.start_time.beginning_of_week - 1.week + 2.days
    end

    self.nfl_start_week = nfl_game.week
    self.nfl_start_week += 17 if nfl_game.season_type_id == 3
    self.nfl_start_week = 1 if nfl_game.season_type_id == 2

    self.start_week_date = data.start_date
    self.start_week_date += (5 - nfl_game.week).weeks if nfl_game.season_type_id == 2

    self.save
  end

  def get_league_week_data_for_week(league_week = nil)
    week_data = get_league_week_data
    league_week = week_data.week_number unless league_week

    return nil if league_week > self.total_weeks or league_week <= 0

    week_data.week_number = 1 if(week_data.week_number == 0)    # 0 is returned when league hasn't started yet

    week_data.start_date += (league_week - week_data.week_number).weeks
    week_data.week_number = league_week
    return week_data
  end

  def get_league_week_data(date = nil)
    start_week = nil
    week = WeekData.new

    if(self.start_week_date)
      start_week = self.start_week_date
    else
      transactions = draft_transactions.to_a
      order = get_draft_order
    end

    if(start_week or transactions.count == order.count)
      # Use the next upcoming Tuesday as the start of week
      start_day_of_week = 2

      unless(start_week)
        # Get last draft pick as league start time and add 1 week if it is on start day of week or later
        max_transaction = transactions.max_by { |t| t.transaction_date }.transaction_date
        max_transaction += 1.week if max_transaction.wday >= start_day_of_week

        start_week = max_transaction
      end

      start_week = (start_week.beginning_of_week.at_beginning_of_day + start_day_of_week.days).to_date

      date = DateTime.now unless date
      date = date.utc.at_beginning_of_day.to_date

      days = (date - start_week).to_i
      if(days < 0)
        week.week_number = 0
        week.start_date = start_week
      else
        week.week_number = (days / 7).floor + 1
        week.start_date = start_week + (week.week_number - 1).weeks
      end
    end

    return week
  end

  def get_nfl_week_game(league_week_data)
    game = nil
    if(league_week_data)
      # Adding extra weeks to end date in case of missing weeks (i.e. skipped week before super bowl)
      games = NflGame.where('start_time between ? and ?', league_week_data.start_date + 1.days, league_week_data.end_date + 2.week + 1.days).order(:start_time)
      if(games.count > 0)
        game = games.first
      end
    end
    return game
  end

  def get_nfl_week_game_from_league_week(league_week)
    week_data = get_league_week_data_for_week(league_week)
    get_nfl_week_game(week_data)
  end

  def is_waiver_period?(now = nil)
    now = Time.now unless now
    now = Time.parse(now) if now.is_a? String
    now = now.utc

    week_data = get_league_week_data(now)
    now < (week_data.start_date + 2.days)
  end

  def get_waiver_order(league_week)
    order = []
    standings = self.team_standings.where(week: league_week).order(:percent, :points_for, points_against: :desc).order("rand()").to_a
  end

  def test_draft()
    set_draft_order

    catchup_draft
    while(true)
      pick = auto_draft_player
      break unless pick
    end
  end

  def catchup_draft
    current_draft_info = self.get_current_draft_info
    while(current_draft_info and current_draft_info.time_left < 0)
      pick = self.auto_draft_player(current_draft_info)
      break unless pick
      current_draft_info = self.get_current_draft_info
    end
  end

  def auto_draft_player(draft_info = nil)
    draft_info = self.get_current_draft_info unless draft_info
    return nil unless draft_info

    slots = self.league_type.get_starting_slots
    round = draft_info.draft_round
    slot = (round - 1) % slots.count
    position = slots[slot].sample

    @position_players = {} unless @position_players
    unless @position_players[position]
      @position_players[position] = NflPlayer.find_position(position).where("nfl_games.season_id between #{season_id} - 1 and #{season_id}")
        .select("nfl_players.*, sum(nfl_game_players.points) as points").group("nfl_players.id").order("points desc").to_a
    end
    players = @position_players[position]

    pick = nil
    @retry_num = 0
    while(pick.nil?)
      begin
        break if @retry_num >= 10

        player = players.slice!(0)

        # Adjust the transaction date in case this draft was made after time expired for that pick
        if(draft_info.time_left < 0)
          transaction_date = draft_info.next_pick_time
        else
          transaction_date = nil
        end
        pick = draft_info.current_team.draft_player(player.id, false, transaction_date)

        #puts "DraftOrder #{draft_info.current_team.draft_order}: Team #{draft_info.current_team.name} drafted position #{position}: #{player.full_name}"
      rescue Exception => e
        if e.message.include?("already taken")
          #puts "DraftOrder #{draft_info.current_team.draft_order}: Team #{draft_info.current_team.name} failed to draft position #{position}: #{player.full_name}"
          #puts "   #{e.message}"
          @retry_num += 1
        else
          raise e
        end
      end
    end

    return pick
  end

  def set_schedule
    return unless self.teams.count == self.size
    return if Game.where(league_id: self.id).count > 0

    league_teams = self.teams.to_a
    weeks = create_schedule
    weeks.each_with_index do |week, week_index|
      week.each_slice(2).to_a.each do |team_game_pair|
        week = (week_index + 1)
        home_team = league_teams[team_game_pair.first - 1].id
        away_team = league_teams[team_game_pair.last - 1].id
        Game.create!(league_id: self.id, week: week, home_team_id: home_team, away_team_id: away_team)
      end
    end
  end

  def create_schedule
    weeks = []

    count = self.size
    unique_weeks = count - 1
    games_per_week = count / 2
    for week in 0...unique_weeks
      for i in 0...games_per_week

        x = (week + i) % (count - 1)
        y = (count - 1 - i + week) % (count - 1)

        if i == 0
          y = count - 1
        end

        weeks.push x + 1
        weeks.push y + 1
      end
    end

    weeks = weeks.each_slice(count).to_a

    remaining_games = (self.weeks - (self.size - 1))
    remaining_games.times do |remaining_week_index|
      weeks.push (weeks[remaining_week_index]).reverse
    end
    weeks
  end

  def set_draft_order
    return unless self.teams.count == self.size
    return if self.teams.first.draft_order

    order = (1..self.size).to_a.shuffle
    self.teams.each_with_index { |team, i|
      team.draft_order = order[i]
      team.save
    }
  end

  def get_draft_order()
    draft_teams = self.teams.order(:draft_order).to_a
    order = []

    self.roster_count.times do
      order += draft_teams
      draft_teams = draft_teams.reverse
    end

    order
  end

  def get_current_draft_info()
    transactions = draft_transactions.to_a
    order = get_draft_order
    info = nil

    if(transactions.count < order.count)
      info = DraftInfo.new
      info.current_team = order[transactions.count]
      info.draft_round =  (transactions.count / self.size).floor + 1
      info.draft_round_pick = (transactions.count % self.size) + 1

      max_transaction = transactions.max_by { |t| t.transaction_date }
      info.last_pick_time = max_transaction.transaction_date if max_transaction
      info.last_pick_time = self.draft_start_date unless max_transaction
      info.last_pick_time = DateTime.now.utc unless info.last_pick_time

      info.next_pick_time = info.last_pick_time + self.draft_pick_time.seconds
    end

    return info
  end
end

app/views/leagues/_join_button.html.erb
<% if signed_in? %>
  <% if league.user_part_of_league?(current_user) %>
    <td class="joined-league">My League!</td>
  <% elsif league.full? %>
    <td class="full-league">League Full</td>
  <% else %>
    <td><%= link_to "Join", join_league_path(league_id: league.id), method: "get", class: "btn btn-success" %></td>
  <% end %>
<% end %>

app/views/leagues/_league_index_table.html.erb
<table class="table table-responsive table-condensed league-index-table">
  <th>Name</th>
  <th>Format</th>
  <th>Duration (Weeks)</th>
  <th>Size</th>
  <th>Available</th>
  <th>Entry</th>
  <th>Draft Date</th>
  <th></th>
  <tbody>
  <% leagues.each do |league| %>
    <tr>
      <td><%= link_to league.name, league %></td>
      <td><%= league.league_type.name %></td>
      <td><%= league.weeks %></td>
      <td><%= league.size %></td>
      <td><%= league.available_teams %></td>
      <td><%= league.entry_amount != 0.00 ? number_to_currency(league.entry_amount) : "FREE" %></td>
      <td><%= league.draft_start_date.in_time_zone("Eastern Time (US & Canada)").strftime("%D %a %l:%M %p %Z") %></td>
      <%= render 'join_button', league: league %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/leagues/_league_standings.html.erb
<table class="table table-responsive table-condensed standings-table">
  <th>Team</th>
  <th>Win</th>
  <th>Loss</th>
  <th>Tie</th>
  <th>PF</th>
  <th>PA</th>
  <th>Streak</th>
  <tbody>
  <% @current_standings.each do |team_standing| %>
    <tr>
      <%= content_tag(:td, link_to(team_standing.team.name, '#', class: highlight_my_team(@user_team, team_standing.team))) %>
      <td><%= team_standing.wins %></td>
      <td><%= team_standing.losses %></td>
      <td><%= team_standing.ties %></td>
      <td><%= team_standing.points_for %></td>
      <td><%= team_standing.points_against %></td>
      <td><%= team_standing.streak %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/leagues/draft.html.erb
<div ng-app="pointsLeaders">
  <div ng-view>
    <%= yield %>
  </div>
</div>

app/views/leagues/index.html.erb
<h1><%= "Leagues".titleize %></h1>

<%= link_to "Create New Traditional league", new_league_path, class: "btn btn-warning" %>
<%= link_to "Create New Weekly league", "#", class: "btn btn-warning" %>

<hr>

<%= render 'league_index_table', leagues: @leagues %>

<%= will_paginate @leagues%>

app/views/leagues/league_info.html.erb
<%= render "shared/league_header" %>
<h1>League Information</h1>

<p><b>Teams</b></p>
<table class="table table-responsive table-condensed draft-info">
  <th>Team Name</th>
  <th>Owner</th>
  <th>Email</th>
  <th>Draft Position</th>
  <tbody>
  <% @league.teams.each do |team| %>
    <tr class=<%= highlight_my_team(@user_team, team) %>>
      <td><%= team.name %></td>
      <td><%= "#{team.user.last_name}, #{team.user.first_name}" %></td>
      <td><%= team.user.email %></td>
      <td><%= team.draft_order %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/leagues/new.html.erb
<h1>Create New Traditional League</h1>

<div class="row">
  <div class="span3">
    <%= form_for(@league) do |f| %>

      <div class="span6">
        <%= render "shared/error_messages", object: @league %>
      </div>

      <h4>Name</h4>
      <%= f.text_field(:name) %>

      <h4>Type</h4>
      <div class="radio">
        <label>
          <% league_type = "Normal" %>
          <% league_type_id = LeagueType.find_by(name: league_type).id %>
          <input type="radio" name="league[league_type]" id="league_type_<%= league_type_id %>" value=<%= league_type_id %> checked>
          <%=league_type%>
        </label>
        <label>
          <% league_type = "Flex 9" %>
          <% league_type_id = LeagueType.find_by(name: league_type).id %>
          <input type="radio" name="league[league_type]" id="league_type_<%= league_type_id %>" value=<%= league_type_id %>>
          <%=league_type%>
        </label>
        <label>
          <% league_type = "Flex 10" %>
          <% league_type_id = LeagueType.find_by(name: league_type).id %>
          <input type="radio" name="league[league_type]" id="league_type_<%= league_type_id %>" value=<%= league_type_id %>>
          <%=league_type%>
        </label>
      </div>
      <hr>

      <h4>Size</h4>
      <div class="league-size">
        <label class="radio inline">
          <input type="radio" name="league[size]" value=10 checked>
          10
        </label>
        <label class="radio inline">
          <input type="radio" name="league[size]" value=12>
          12
        </label>
        <label class="radio inline">
          <input type="radio" name="league[size]" value=14>
          14
        </label>
      </div>
      <hr>

      <h4>Duration</h4>
      <div class="league-size">
        <label class="radio inline">
          <input type="radio" name="league[duration]" value=13 checked>
          13
        </label>
      </div>
      <hr>

      <h4>Entry Amount</h4>
      <div class="entry">
        <% min_entry = 0 %>
        <text id="extracted-fee-amount">FREE</text>
        <%= f.range_field(:entry_amount, min: min_entry, max: 1000, step: 25, id: "entry-slider") %>
      </div>

      <hr>
      <h4>Draft Info</h4>
      <label>
        Date
        <div class="draft-date">
          <input type="text" id="draft-date" name="league[draft_start_date]" value=<%= Time.now %>/>
        </div>
      </label>

      <div class="input-append bootstrap-timepicker">
        <input id="timepicker1" type="text" name=league[draft_time] class="input-small">
        <span class="add-on"><i class="icon-time"></i></span>
      </div>

      <label>
        Draft Pick Time(In Seconds)
        <div class="draft-pick-time">
          <%= f.number_field(:draft_pick_time, min: 120, max: 600, step: 30) %>
        </div>
      </label>

      <hr>

      <h4>Rules</h4>
      <div class="checkbox rules-options">
        <label>
          <input type="checkbox" name=league[ppr] value="1">
          Points per reception?
          <span class="ppr-info"><i class="icon-info-sign"></i></span>
          <div id="ppr-info-popup">
            <p>League will be set with 0.5 points per reception</p>
          </div>
        </label>
      </div>
      <hr>

      <h4>Visibility</h4>
      <div class="league-visibility">
        <label class="radio inline">
          <input type="radio" name="league[visibility]" value=0 checked>
          Public
        </label>
        <label class="radio inline">
          <input type="radio" name="league[visibility]" value=1 >
          Private
        </label>
      </div>
      <hr>

      <%= f.submit("Create League", class: "btn btn-primary") %>
    <% end %>
  </div>
</div>

app/views/leagues/schedule.html.erb
<%= render "shared/league_header" %>
<h1>League Schedule</h1>

<% if @league.available_teams == 0 %>
  <%= render 'shared/weekbar', ajax_path: schedule_league_path, start_week: 1, end_week: @league.weeks %>

  <div class="weekly-league-info"></div>

<% else %>
    <h3 class="center highlight">League not full yet... only <%= @league.available_teams %> slots to go!</h3>
<% end %>

app/views/leagues/show.html.erb
<%= render "shared/league_header" %>

<p><b>Current Week: <%= @current_week %></b></p>

<div class="draft-start-time">
  <h3>
    Draft Begins on: <b> <%= @league.draft_start_date.in_time_zone("Eastern Time (US & Canada)").strftime("%D %a %l:%M %p %Z") %></b>
  </h3>
</div>

<p>NFL News</p>
<p>League News</p>
<p>Standings</p>

<td><%= link_to "Leave League", league_team_path(@league, @user_team), method: "delete", class: "btn btn-danger" %></td>

app/views/leagues/standings.html.erb
<%= render "shared/league_header" %>
<h1>League Standings</h1>

<%= render 'shared/weekbar', ajax_path: standings_league_path ,start_week: 1, end_week: @league.weeks %>

<div class="weekly-league-info">
</div>