config/routes.rb
FantasyFootball::Application.routes.draw do

  root "fantasy_football#home"

  resources :leagues, param: :league_id, only: [:index, :show, :new, :create] do
    member do
      get :schedule
      get :standings
      get :league_info
      get :draft
    end
    resources :teams, param: :team_id, only: [:show, :destroy] do
      get :schedule, on: :collection
      get :set_lineup, on: :member
    end
  end

  match "/join_league", to: "leagues#join", via: "get", as:"join_league"

  resources :sessions, only: [:new, :create, :destroy], path_names: { new: 'signin', destroy: 'signout' }
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"

  resources :users, except: [:index]
  match "/users/email_exists/:email_address", to: "users#email_exists", via: "get", constraints: { :email_address => /[^\/]+/ }
  match "/signup", to: "users#new", via: "get"


  namespace :api, path: '/v1', constraints: { subdomain: 'api' } do
    resources :players, only: [:index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase.strip }
  before_create :create_remember_token
  after_save :signup_success_notification, if: :id_changed?

  has_secure_password

  has_many :teams
  has_many :leagues, :through => :teams
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :uniqueness => true,
            :presence => true, :length => { maximum: 50 },
            :format => { :with => VALID_EMAIL_REGEX }

  validates :password, :length => { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

    def signup_success_notification
      UserMailer.signup_success(self).deliver
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def show
    @user_leagues = @user.leagues
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome #{@user.first_name} to Fantasy Football!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    render 'new'
  end

  def update
    if @user.update_attributes(edit_user_params)
      flash[:success] = "User updated successfully"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
  end

  def email_exists
    result = User.exists?(email: params[:email_address])
    result = 0 unless result
    render text: result
  end
end

private

  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :address, :city, :zip,
                                 :password, :password_confirmation)
  end

  def edit_user_params
    params.require(:user).permit(:first_name, :last_name, :address, :city, :zip, :password, :password_confirmation)
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Current User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>

        <div class="control-group control-group-email">
          <%= f.label :email, "Email Address", class: "required" %>
          <%= f.text_field :email, class: "email" %>
          <span class="error-message error-required"> Email Address is required </span>
          <span class="error-message error-taken"> Email Address already taken </span>
          <span class="error-message error-invalid-format"> Email Address format is invalid (i.e. name@domain.com) </span>
        </div>

        <div class="control-group control-group-password">
          <%= f.label :password, "Password", class: "required" %>
          <%= f.password_field :password, class: "password" %>
          <span class="error-message password-short"> Passwords must be over 6 characters long </span>

          <%= f.label :password_confirmation, "Password Confirmation", class: "required" %>
          <%= f.password_field :password_confirmation, class: "password-confirmation" %>
          <span class="error-message password-mismatch"> Passwords do not match </span>
        </div>

        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>

        <%= f.label :address, "Address" %>
        <%= f.text_field :address %>

        <%= f.label :city, "City" %>
        <%= f.text_field :city %>

        <%= f.label :state, "State" %>
        <%= f.text_field :state %>

        <%= f.label :zip, "Zip Code" %>
        <%= f.text_field :zip %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>WELCOME TO FANTASY FOOTBALL</h1>

<div class="center">
  <button> <%= link_to "Sign Up Here!", new_user_path %> </button>
</div>

app/views/users/new.html.erb
<% @action_name = signed_in? ? "Update" : "Create" %>

<h1><%= @action_name %> User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages", object: @user %>
        <div class="control-group control-group-email">
            <% if signed_in? %>
                <label>Email Address</label>
                <div>
                    <label class="span6"><%= @user.email %></label>
                </div>
            <% else %>
                <%= f.label :email, "Email Address", class: "required" %>
                <%= f.text_field :email, class: "email" %>
                <span class="error-message error-required"> Email Address is required </span>
                <span class="error-message error-taken"> Email Address already taken </span>
                <span class="error-message error-invalid-format"> Email Address format is invalid (e.g. name@domain.com) </span>
            <% end %>
        </div>

        <div class="control-group control-group-password">
            <%= f.label :password, "Password", class: "required" %>
            <%= f.password_field :password, class: "password" %>
            <span class="error-message password-short"> Passwords must be over 6 characters long </span>

            <%= f.label :password_confirmation, "Password Confirmation", class: "required" %>
            <%= f.password_field :password_confirmation, class: "password-confirmation" %>
            <span class="error-message password-mismatch"> Passwords do not match </span>
        </div>

        <div class="registration-name">
          <div class="name1">
            <%= f.label :first_name, "First Name" %>
            <%= f.text_field :first_name %>
          </div>
          <div class="name2">
            <%= f.label :last_name, "Last Name" %>
            <%= f.text_field :last_name %>
          </div>
        </div>


        <% if signed_in? %>
            <%= f.label :address, "Address" %>
            <%= f.text_field :address %>

            <%= f.label :city, "City" %>
            <%= f.text_field :city %>

            <%= f.label :state, "State" %>
            <%= f.text_field :state %>

            <%= f.label :zip, "Zip Code" %>
            <%= f.text_field :zip %>
        <% end %>
        <%= f.submit "#{@action_name} User", class: "btn btn-large btn-primary" %>
    <% end %>
      </div>
    </div>

app/views/users/show.html.erb
<h1> <%= "#{@user.first_name} #{@user.last_name}'s Profile" %> </h1>

<% if @user_leagues.count > 0 %>
  <h3>My Leagues</h3>
  <table class="table table-responsive table-condensed">
    <th>Name</th>
    <th>Format</th>
    <th>Draft Date</th>
    <th>Current Week</th>
    <th>Weeks Remaining</th>
    <th>Rank</th>
    <th>Entry</th>
    <th>Payout</th>
    <tbody>
    <% @user_leagues.each do |league| %>
      <tr>
        <td><%= link_to league.name, league %></td>
        <td><%= league.league_type.name %></td>
        <td><%= league.draft_start_date.in_time_zone("Eastern Time (US & Canada)").strftime("%D %a %l:%M %p %Z") %></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= league.entry_amount != 0.00 ? number_to_currency(league.entry_amount) : "FREE" %></td>
        <td></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No current leagues</p>
  <%= link_to "Join a League", leagues_path, class: "btn btn-success" %>
<% end %>