config/routes.rb
FantasyFootball::Application.routes.draw do

  root "fantasy_football#home"

  resources :leagues, param: :league_id, only: [:index, :show, :new, :create] do
    member do
      get :schedule
      get :standings
      get :league_info
      get :draft
    end
    resources :teams, param: :team_id, only: [:show, :destroy] do
      get :schedule, on: :collection
      get :set_lineup, on: :member
    end
  end

  match "/join_league", to: "leagues#join", via: "get", as:"join_league"

  resources :sessions, only: [:new, :create, :destroy], path_names: { new: 'signin', destroy: 'signout' }
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"

  resources :users, except: [:index]
  match "/users/email_exists/:email_address", to: "users#email_exists", via: "get", constraints: { :email_address => /[^\/]+/ }
  match "/signup", to: "users#new", via: "get"


  namespace :api, path: '/v1', constraints: { subdomain: 'api' } do
    resources :players, only: [:index, :show]
  end
end

app/views/shared/_dropdown_menu_item.html.erb
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <%= menu_data[:menu_name] %> <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% menu_data[:menu_items].each do |menu_item| %>
      <li><%= link_to menu_item[:item_name], menu_item[:item_path] %></li>
    <% end %>
  </ul>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>:
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_league_header.html.erb
<ul class="nav nav-tabs league-nav">
  <li><%= link_to "Home", league_path(@league) %></li>
  <li><%= link_to "My Team", league_team_path(@league, @user_team) %></li>
  <li><%= link_to "Live Scoring", "#" %></li>
  <li><%= link_to "Standings", standings_league_path(@league) %></li>

  <%= render "shared/dropdown_menu_item", menu_data: { menu_name: "Schedules",
                                                       menu_items: [ { item_name: "League Schedule", item_path: schedule_league_path(@league) },
                                                                     { item_name: "Team Schedule", item_path: schedule_league_teams_path(@league) } ]
                                                     } %>

  <li><%= link_to "Free Agency", "#" %></li>
  <li><%= link_to "Trades", "#" %></li>
  <li><%= link_to "Stat Central", "#" %></li>

  <%= render "shared/dropdown_menu_item", menu_data: { menu_name: "League Info",
                                                       menu_items: [ { item_name: "Settings", item_path: "#" },
                                                                     { item_name: "Teams", item_path: league_info_league_path(@league) },
                                                                     { item_name: "Rules", item_path: "#" } ]
                                                     } %>
</ul>

app/views/shared/_teams_select.html.erb
<%= tag("div", data: { league: @league.id }, class: "user-combobox") %>
<label for="team_id" style="font-size: 17px">Team:
    <%= form_tag(remote: true) do %>
        <% values = @league.teams.map { |team| [team.name, team.id] }%>
        <% options = options_for_select(values) %>
        <%= select(:team, :id, options) %>
    <% end %>
</label>
</div>

app/views/shared/_weekbar.html.erb
<div class="btn-group week-bar" role="toolbar" data-current-week=<%= @current_week %>>
  <% for week_number in start_week..end_week %>
    <%= link_to("week #{week_number}", "#{ajax_path}?current_week=#{week_number}", class: "btn btn-default") %>
  <% end %>
</div>