config/routes.rb
FantasyFootball::Application.routes.draw do

  root "fantasy_football#home"

  resources :leagues, param: :league_id, only: [:index, :show, :new, :create] do
    member do
      get :schedule
      get :standings
      get :league_info
      get :draft
    end
    resources :teams, param: :team_id, only: [:show, :destroy] do
      get :schedule, on: :collection
      get :set_lineup, on: :member
    end
  end

  match "/join_league", to: "leagues#join", via: "get", as:"join_league"

  resources :sessions, only: [:new, :create, :destroy], path_names: { new: 'signin', destroy: 'signout' }
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"

  resources :users, except: [:index]
  match "/users/email_exists/:email_address", to: "users#email_exists", via: "get", constraints: { :email_address => /[^\/]+/ }
  match "/signup", to: "users#new", via: "get"


  namespace :api, path: '/v1', constraints: { subdomain: 'api' } do
    resources :players, only: [:index, :show]
  end
end

app/views/layouts/_flash_alerts.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About Us",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "How It Works", '#' %></li>
      <li><%= link_to "Help", '#' %></li>
      <li><%= link_to "Terms of Service", '#' %></li>
      <li><%= link_to "Privacy Policy", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% @logo_path = current_user ? current_user : root_path %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <%= link_to "Points Leaders", @logo_path, id: "logo" %>
        <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Leagues", leagues_path %></li>
            <% if signed_in? %>
                <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Add Funds", "#" %></li>
                  <li><%= link_to "My Profile", current_user %></li>
                  <li><%= link_to "User Settings",edit_user_path(current_user) %></li>
                  <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
                </ul>
            <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyFootball</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/flash_alerts' %>
    <%= yield %>
  </div>
</body>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</html>